import { Schema } from 'koishi'
import path from 'path'

export interface RenderColors {
  primaryColor: string
  cardBgColor: string
  statusOngoingColor: string
  statusNextColor: string
  statusFinishedColor: string
}

export const defaultColors: RenderColors = {
  primaryColor: '#52449e',
  cardBgColor: '#E3F2FD',
  statusOngoingColor: '#D32F2F',
  statusNextColor: '#1976D2',
  statusFinishedColor: '#388E3C',
}

export const RenderColorsSchema = Schema.object({
  primaryColor: Schema.string().role('color').default('#52449e').description('🎨 主题色（左侧装饰竖线）'),
  cardBgColor: Schema.string().role('color').default('#E3F2FD').description('📋 个人课表卡片背景色'),
  statusOngoingColor: Schema.string().role('color').default('#D32F2F').description('🔴 进行中状态标签色'),
  statusNextColor: Schema.string().role('color').default('#1976D2').description('🔵 下一节状态标签色'),
  statusFinishedColor: Schema.string().role('color').default('#388E3C').description('🟢 已结束状态标签色'),
})

export interface Config {
  // 💬 消息设置
  enableQuote: boolean
  enableWatingHint: boolean
  bindPromptText: string

  // ⚙️ 指令设置
  baseCommand: string
  bindCommand: string
  showCommand: string
  groupCommand: string
  rankingCommand: string
  weekCommand: string

  // 🖼️ 渲染设置
  renderWaitUntil: 'load' | 'domcontentloaded' | 'networkidle0' | 'networkidle2'
  textFontPath: string
  renderFooterText: string

  // 📁 文件设置
  icsTempDir: string
  icsTempDeleteTime: number

  // 🎨 渲染颜色设置
  renderColors: RenderColors

  // 🐛 调试设置
  verboseConsoleLog: boolean
}

export const Config: Schema<Config> = Schema.intersect([

  // 💬 消息设置
  Schema.object({
    enableQuote: Schema.boolean().default(true).description('💬 开启后，本插件发送的所有消息都会引用回复触发指令的消息'),
    enableWatingHint: Schema.boolean().default(true).description('⏳ 是否启用「渲染中，请稍候...」提示消息'),
    bindPromptText: Schema.string().default('📥 请发送 WakeUp 分享文本、ICS 文本、课表 JSON，或附带 .ics/.json/.wakeup_schedule 文件。\n\n⚠️ 注意：WakeUp 课程表高版本已对 API 加强限制 🔒，版本号高于 6.1.x 的 WakeUp 课程表无法通过分享口令绑定。\n\n🔧 推荐降级到作者同款版本 6.0.23 ⬇️：\nhttps://gitee.com/vincent-zyu/koishi-plugin-course-schedule/releases/download/WakeUp6.0.23/WakeUp_6.0.23.apk').role('textarea', { rows: [3, 10] }).description('📝 绑定指令触发交互式等待时发送的提示文本（支持换行）'),
  }).description('💬 消息设置'),

  // ⚙️ 指令设置
  Schema.object({
    baseCommand: Schema.string().default('课表').description('父级指令名称'),
    __split__: Schema.string().disabled().default('上面是父级指令，下面是字指令').description('_____————上面是父级指令，下面是字指令————_____'),
    bindCommand: Schema.string().default('绑定').description('绑定课表命令名'),
    showCommand: Schema.string().default('查看').description('查看个人课表命令名'),
    groupCommand: Schema.string().default('群课表').description('查看群友课表命令名'),
    rankingCommand: Schema.string().default('排行').description('查看本周排行命令名'),
    weekCommand: Schema.string().default('周课表').description('查看周课表命令名'),
  }).description('⚙️ 指令设置'),

  // 🖼️ 渲染设置
  Schema.object({
    renderWaitUntil: Schema.union([
      Schema.const('load').description('【load】等待页面与静态资源加载完成，适合当前纯本地 HTML 渲染'),
      Schema.const('domcontentloaded').description('【domcontentloaded】只等待 DOM 构建完成，速度快但更容易过早截图'),
      Schema.const('networkidle0').description('【networkidle0】等待网络连接归零，适合依赖外部资源的页面'),
      Schema.const('networkidle2').description('【networkidle2】等待网络基本空闲，介于 load 与 networkidle0 之间'),
    ]).default('load').description('🖼️ Puppeteer setContent 的 waitUntil 策略'),
    textFontPath: Schema.string().default('').role('textarea', { rows: [2, 5] }).description('🔤 文字字体文件路径（绝对路径，留空则使用系统默认字体）'),
    renderFooterText: Schema.string().default('📚📅🤖 Generated by koishi-plugin-course-schedule\n🌐 Gitee repo: https://gitee.com/vincent-zyu/koishi-plugin-course-schedule').role('textarea', { rows: [3, 10] }).description('📝 图片底部文字（支持换行，留空则不显示）'),
  }).description('🖼️ 渲染设置'),

  // 📁 文件设置
  Schema.object({
    icsTempDir: Schema.string().default(path.resolve(__dirname, '..', 'tmp')).role('textarea', { rows: [2, 5] }).description('📁 ICS 临时文件目录（绝对路径）'),
    icsTempDeleteTime: Schema.number().default(300).description('🗑️ 临时 ICS 文件删除时间（秒），0 或负数表示永不删除'),
  }).description('📁 文件设置'),

  // 🎨 渲染颜色设置
  Schema.object({
    renderColors: RenderColorsSchema,
  }).role('table').default({ renderColors: defaultColors }).description('🎨 渲染颜色设置'),

  // 🐛 调试设置
  Schema.object({
    verboseConsoleLog: Schema.boolean().default(false).description('📋 详细控制台调试日志'),
  }).description('🐛 调试设置'),
])
